artifacts: 
  discard-paths: true
  files: 
    - html/**/*
    - ftpfiletos3_lint.html
    - lambda_functions_lint.html
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - run_tests_generate_html_coverage_report
  install: 
    commands: 
      - "pip install pytz"
      - "pip install pylint"
      - "pip install coverage"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
  pre_build: 
    commands: 
      - "echo Pre Build phase started on `date`"
      - "chomd +x static_code_analysis/*"
      - "chmod +x run_tests_generate_html_coverage_report"
      - static_code_analysis/pylint-ftpfiletos3
      - static_code_analysis/pylint-lambda-functions
version: 0.1