#!/bin/bash
pidfile="/tmp/ftpfiletos3.pid"
if [ -e "$pidfile" ]
then
    /bin/kill $(cat "$pidfile")
    /bin/rm -Rf "$pidfile" 
fi
sleep 2
/usr/bin/python /home/brian.roy/brian-extra/sendftpfilestos3/ftpfiletos3.py /home/brian.roy/brian-extra/sendftpfilestos3/vsftpd-config.json > /dev/null &