#!/bin/bash
pidfile="/tmp/ftpfiletos3.pid"
if [ -e "$pidfile" ]
then
    /bin/kill $(cat "$pidfile")
    /bin/rm -Rf "$pidfile" 
fi
sleep 2
/usr/local/bin/ftpfiletos3.py /etc/ftpfiles2s3-vsftpd-config.json > /dev/null &
